//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace InvoiceInput.Module.BusinessObjects.Database
{

    [Persistent(@"2016")]
    public partial class P_2016 : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string f备注;
        [Size(255)]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>("备注", ref f备注, value); }
        }
        string f币种;
        [Size(255)]
        public string 币种
        {
            get { return f币种; }
            set { SetPropertyValue<string>("币种", ref f币种, value); }
        }
        string f草单编号;
        [Size(255)]
        public string 草单编号
        {
            get { return f草单编号; }
            set { SetPropertyValue<string>("草单编号", ref f草单编号, value); }
        }
        double f代理费;
        public double 代理费
        {
            get { return f代理费; }
            set { SetPropertyValue<double>("代理费", ref f代理费, value); }
        }
        double f翻译;
        public double 翻译
        {
            get { return f翻译; }
            set { SetPropertyValue<double>("翻译", ref f翻译, value); }
        }
        double f官费;
        public double 官费
        {
            get { return f官费; }
            set { SetPropertyValue<double>("官费", ref f官费, value); }
        }
        DateTime f核准日;
        public DateTime 核准日
        {
            get { return f核准日; }
            set { SetPropertyValue<DateTime>("核准日", ref f核准日, value); }
        }
        DateTime f记账日期;
        public DateTime 记账日期
        {
            get { return f记账日期; }
            set { SetPropertyValue<DateTime>("记账日期", ref f记账日期, value); }
        }
        string f卷号;
        [Size(255)]
        public string 卷号
        {
            get { return f卷号; }
            set { SetPropertyValue<string>("卷号", ref f卷号, value); }
        }
        string f项目;
        [Size(255)]
        public string 项目
        {
            get { return f项目; }
            set { SetPropertyValue<string>("项目", ref f项目, value); }
        }
        double f杂费;
        public double 杂费
        {
            get { return f杂费; }
            set { SetPropertyValue<double>("杂费", ref f杂费, value); }
        }
        string f债方;
        [Size(255)]
        public string 债方
        {
            get { return f债方; }
            set { SetPropertyValue<string>("债方", ref f债方, value); }
        }
        string f账单号;
        [Size(255)]
        public string 账单号
        {
            get { return f账单号; }
            set { SetPropertyValue<string>("账单号", ref f账单号, value); }
        }
        string f正式账单;
        [Size(255)]
        public string 正式账单
        {
            get { return f正式账单; }
            set { SetPropertyValue<string>("正式账单", ref f正式账单, value); }
        }
        DateTime f指定请款日;
        public DateTime 指定请款日
        {
            get { return f指定请款日; }
            set { SetPropertyValue<DateTime>("指定请款日", ref f指定请款日, value); }
        }
        double f总计;
        public double 总计
        {
            get { return f总计; }
            set { SetPropertyValue<double>("总计", ref f总计, value); }
        }
    }

}
